#!/bin/sh
re='^[0-9]{3}$'
NUMBER=100
type=g

## Fuction 'usage', displays usage information
usage()
{
cat << EOF
usage: $0 options

This script retrives information of the TPB, in top list views.

OPTIONS:
   -h      Show this message
   -c      Category                 (Syntax is a 3 digit number)
   -n      Number of entries        (Default is 100 - i.e. a Top 100 list)
   -d      Download give number
   -s      Short list view

EOF
}

getlist()
{
curl -L -s http://thepiratebay.org/top/$CATEGORY | \
grep -E '("detName|Magnet link|Uploaded|td align)' | \
sed -e 's/&nbsp;/ /g' \
    -e 's/^.*Uploaded \(.*\), Size \(.*\), ULed.*/uploaded = "\1"#size = "\2"/' \
    -e 's/^.*detName.*\">\(.*\)<\/a>/titel = "\1"/' \
    -e 's/^.*"\(magnet\:.*\)" title="Download this torrent using magnet.*/\1/' \
    -e 's/^.*td align=.right..\(.*\)..td.*/\1/' | \
tr '#' '\n' | \
head -n $(expr 6 \* $NUMBER) > /tmp/tmp_top.txt
}

while getopts “hsdc:n:” OPTION
do
     case $OPTION in
         h)
             usage
             exit 0
             ;;
         s)
             type=s
             ;;
         d)
             type=d
             ;;
         c)
             CATEGORY=$OPTARG
             ;;
         n)
             NUMBER=$OPTARG
             ;;
         ?)
             usage
             exit
             ;;
     esac
done


if ! [[ $CATEGORY =~ $re ]]
	then 
	usage
	exit 1
fi

getlist

case "$type" in
	s)
		## Short list view
		cat /tmp/tmp_top.txt | grep "^titel" | sed -e 's/titel = "//' -e 's/"//' | nl
		;;
	d)
		## Download the given number
		btc add -u "$(cat /tmp/tmp_top.txt | grep "^magnet" | tail -n 1)"
		;;
	g)
		cat /tmp/tmp_top.txt
		;;
esac

rm /tmp/tmp_top.txt
